// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO0t3bfCVTQ-NzdLBZfSYpcMoNNRb6Euo',
    appId: '1:641987734333:web:2d2e0eccdd5e004eb07354',
    messagingSenderId: '641987734333',
    projectId: 'newdatabase-2956b',
    authDomain: 'newdatabase-2956b.firebaseapp.com',
    storageBucket: 'newdatabase-2956b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4MzdQJSAgfyRi6oc9oMNJNg_UISdsUdU',
    appId: '1:641987734333:android:64c7cf2f5b1e326bb07354',
    messagingSenderId: '641987734333',
    projectId: 'newdatabase-2956b',
    storageBucket: 'newdatabase-2956b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ0NJTRjZMRIuX2_WbU1Fj5WnWbSVS6i0',
    appId: '1:641987734333:ios:7a4a13c0a6ac7d84b07354',
    messagingSenderId: '641987734333',
    projectId: 'newdatabase-2956b',
    storageBucket: 'newdatabase-2956b.firebasestorage.app',
    iosBundleId: 'com.example.geoReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ0NJTRjZMRIuX2_WbU1Fj5WnWbSVS6i0',
    appId: '1:641987734333:ios:7a4a13c0a6ac7d84b07354',
    messagingSenderId: '641987734333',
    projectId: 'newdatabase-2956b',
    storageBucket: 'newdatabase-2956b.firebasestorage.app',
    iosBundleId: 'com.example.geoReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO0t3bfCVTQ-NzdLBZfSYpcMoNNRb6Euo',
    appId: '1:641987734333:web:6821010297d1ba2eb07354',
    messagingSenderId: '641987734333',
    projectId: 'newdatabase-2956b',
    authDomain: 'newdatabase-2956b.firebaseapp.com',
    storageBucket: 'newdatabase-2956b.firebasestorage.app',
  );
}
